language: python
python:
  - "3.6.x"  # 3.6 development branch
  - "3.7.x"  # 3.7 development branch

install:
  - pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: pypi
  user: ...
  password: ...
  on:
    tags: true